### PR TITLE
[WIP][INFRA-1782][INFRA-2027] Build a custom datadog docker image with custom checks

### PR DESCRIPTION
**Pull request by olblak**
- [x] INFRA-2027
- [x] INFRA-1782
- [x] Automated image build
- [x] Deploy image on k8s

### CODE REVIEW

**Comment by mpailloncy** [comment]
Just to be sure @olblak, do you want me to review ? or do you still have some bits to move?

**Comment by olblak** [comment]
Still some bits to move, you were automagically assigned :D

**Comment by mpailloncy** [comment]
yeah, no problem :) let me know when you need my eyes

**Comment by mpailloncy** [comment]
I could have added some comments here Olivier

**Pull request merged**
